### ISSUE TITLE
Add back source code on NPM packages

### ISSUE THREAD

**Issue by zeroseed** [GovTechSG/sgds#124]
# Expected Behavior

On npm packages you should include source code files too, instead of only compiled css / js, so we can use separate sass file , not the whole. Why ? because every project is unique, you can't just change it all. it will break current components while we just want to use the sgds masthead, header style, or icons only.

# Current Behavior

Current behavior after npm install on node_modules folder I just found compiled css / js files only. Cannot use it as separate saas file.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npm install sgds-govtech
2. Look on node_modules/sgds-govtech folder

**Comment by weijunyu** [comment]
Hi @zeroseed, we've just published version **1.3.6** which contains the sass files.
After running your npm install, you can find them under `sgds-govtech/sgds/sass`.

Thank you

**Comment by zeroseed** [comment]
Thanks @weijunyu  !!
