### ISSUE TITLE
Buttons located under hero do not have strong clickable signifiers

### ISSUE THREAD

**Issue by Sylphias** [GovTechSG/sgds#13]
Without mousing over the 3 tabs, it is hard to tell that the buttons are clickable.
![image](https://user-images.githubusercontent.com/5444382/62278109-01293b80-b47a-11e9-88a2-c5aeaf0f4967.png)

Perhaps it is worth looking into creating a stronger affordance for click-ability on these buttons

**Comment by rav3** [comment]
Added **right chervon icon** to emphasis clickable
![Screenshot 2019-08-19 at 1 38 23 PM](https://user-images.githubusercontent.com/6713735/63241528-a6b81980-c286-11e9-8f39-cb3aa0afa1a3.png)
