### ISSUE TITLE
Govt Masthead causes page to have additional padding to the right and bottom

### ISSUE THREAD

**Issue by es-lynn** [GovTechSG/sgds#414]
# Expected Behavior

Govt Masthead should not be larger than the `<body>` itself.

# Current Behavior

Govt Masthead causes the page to be larger than original body.

![sgds](https://user-images.githubusercontent.com/7008316/195304948-bf0d0360-3487-4858-ae7b-56d41c979645.gif)

# Failure Information (for bugs)

This appears to be caused by the following two elements:

```
.columns {
    margin-left: -0.75rem;
    margin-right: -0.75rem;
}

.container {
  --sgds-masthead-tablet-padding-x: 1.25rem
}
```

## Steps to Reproduce

I've attached 2 files:
- index-with-masthead.html
- index-without-masthead.html

[index-html.zip](https://github.com/GovTechSG/sgds/files/9763472/index-html.zip)

1. Open `index-with-masthead` in chrome
2. Set the view to mobile view (iPad Air)
3. Scroll to the right and bottom. There should be additional padding on the right and bottom.
 
This problem does not occur in `index-without-masthead`.

## Context

I was trying to embed the Govt Masthead to a webpage. However after adding it, I noticed that there was additional padding on the right. After some debugging, I determined it was caused by the Govt Masthead. Even after starting a blank .html page with nothing, the issue still occurs.

## Failure Logs

N/A

**Comment by cflee** [comment]
This bug is still present in the current release 0.0.11 of [sgds-masthead-react](https://github.com/GovTechSG/sgds-masthead/tree/master/sgds-masthead-react).
