### ISSUE TITLE
Navbar Dropdowns are broken when Navbar expand is smaller than large

### ISSUE THREAD

**Issue by cflee** [GovTechSG/sgds#461]
# Expected Behavior

Navbar Dropdowns on a Navbar with `expand="md"` are rendered correctly at the medium breakpoint, without being hidden by a vertical scroll.

# Current Behavior

Navbar Dropdowns on a Navbar with `expand="md"` are hidden by a vertical scroll.

This occurs with values of `expand` that are smaller than large.

https://github.com/GovTechSG/sgds/blob/v2.1.0/sass/_navbar.scss#L7-L10

This was introduced in v2.1.0 #396 

## Steps to Reproduce

1. Go to https://react.designsystem.tech.gov.sg/?path=/story/components-navigation-navbar--basic&args=fixed:top;expand:md
2. Ensure that the expand prop is set to `"md"` (or `"sm"`)
3. On the canvas, adjust the width until it is just slightly wide enough to switch from the collapsed version to the expanded version, and the "Dropdown" and "Megamenu" are visible
4. Click on the "Dropdown"
5. Observe that the dropdown is hidden inside a vertical scroll
  ![image](https://github.com/GovTechSG/sgds/assets/8225175/fd9868bb-5af1-4b9f-bfb2-272295db1b5e)

6. Increase the width until it hits large breakpoint, and the dropdown renders appropriately
  ![image](https://github.com/GovTechSG/sgds/assets/8225175/5eed5e75-937c-4290-8fd6-404b714a34fc)

**Comment by th-94** [comment]
This issue happens when `overflow-x: scroll` applied to `navbar` class below 992px viewport width. Will remove the styling as it is unnecessary.

This issue is related to #462, fixing this will fix the issue too.
