### ISSUE TITLE
Potential typo in copywriting

### ISSUE THREAD

**Issue by zillding** [GovTechSG/sgds#499]
# Expected Behavior

'SGDS uses ...'

# Current Behavior

'SGDS users ...'

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. go to https://www.designsystem.tech.gov.sg/foundations/typography
2. see the typo under 'Font family'

**Comment by rav3** [comment]
@zillding
Thanks for spotting the grammar.
