### ISSUE TITLE
Tooltip not working if child Button is disabled

### ISSUE THREAD

**Issue by pohti** [GovTechSG/sgds#506]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Describe the issue

For [Tooltip (react version) ](https://react.designsystem.tech.gov.sg/?path=/docs/components-tooltip--basic)
I noticed that the Tooltip also stops working when the child Button is disabled.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-react are you using? CSR or SSR?

@govtechsg/sgds-react: 2.6.0 and react: 18.2.0

**Comment by clukhei** [comment]
@pohti please update @govtechsg/sgds repo to v2.3.4

https://github.com/GovTechSG/sgds/releases/tag/v2.3.4
