### ISSUE TITLE
Enable Y-Axis Scrolling for Combo Box Dropdown Menus

### ISSUE THREAD

**Issue by elsonlim** [GovTechSG/sgds#508]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Proposal

<img width="457" alt="image" src="https://github.com/user-attachments/assets/144cebe6-0e0d-4763-9051-cdc3915be544">

Propose adding support for vertical (Y-axis) scrolling within the dropdown menu of combo boxes. This enhancement would allow users to easily navigate through long lists of items, especially when the dropdown menu exceeds the available screen space.
 
Scrolling flag: Introduce a new property or configuration setting (e.g., enableScrolling or scrollable) that allows developers to explicitly enable or disable Y-axis scrolling for the combo box dropdown menu. The default behaviour could be disabled to avoid breaking change.

Customisation options: Developers should have the ability to customise the maximum height of the dropdown menu, the appearance of the scrollbar, and other relevant styling options.

### Motivation and context

Long dropdown menus in combo boxes can pose usability challenges, particularly when they extend beyond the visible screen area. Users may have to resize the window or scroll the entire page to view all the options, which can be frustrating and inefficient.

<img width="550" alt="image" src="https://github.com/user-attachments/assets/582430bb-7d09-4cae-ac64-13eb5e4e078e">

**Comment by clukhei** [comment]
Hi @elsonlim, this enhancements seats closer with the style repository behind @govtechsg/sgds-react 
I will transfer this issue to that repository.

**Comment by clukhei** [comment]
@elsonlim do note that the customisation of height can be made possible, but it has to be done through SASS as this repo is written in SASS. We will give a default of 480px max-height when the combobox menu is scrollable

**Comment by elsonlim** [comment]
Thanks, @clukhei. That will be very helpful!

**Comment by clukhei** [comment]
@elsonlim please update `@govtechsg/sgds` to version v2.3.4 and `@govtechsg/sgds-react` to v2.7.0 to get these changes. 

https://github.com/GovTechSG/sgds/releases/tag/v2.3.4
