### ISSUE TITLE
scss error

### ISSUE THREAD

**Issue by min-marn-oo-hive** [GovTechSG/sgds#525]
# Our setup

We import "~@govtechsg/sgds/sass/sgds.scss" from the root scss file "main.scss" and reuse the sgds scss variables across our project.

# Current Behavior

After updating `@govtechsg/sgds` from version `2.3.4` to `2.3.5`, we started seeing the error in the attached screenshot.

# Failure Information (for bugs)

After doing some tracing, it seems to be that sass-loader (v14.2.1) sees the implementation in the _variables.scss of sgds as deprecated.

![Screenshot 2024-12-17 at 2 01 23 PM](https://github.com/user-attachments/assets/b59c553f-363c-4a7e-9516-ce54687f4bb2)

**Comment by clukhei** [comment]
@min-marn-oo-hive thanks for raising the issue. Fixes deployed in v2.3.6 of the library
