### ISSUE TITLE
Lack of documentation for Pagination features

### ISSUE THREAD

**Issue by Sylphias** [GovTechSG/sgds#60]
No documentation for usage of pagination components
![image](https://user-images.githubusercontent.com/5444382/63335556-2e2d8780-c370-11e9-9d52-49e91e4109cb.png)
![image](https://user-images.githubusercontent.com/5444382/63335576-3685c280-c370-11e9-8813-29a37498de5b.png)

**Comment by rav3** [comment]
Fixing is-centered and is-right for pagination compoment
